#!/bin/bash
DISPLAY=":$1"
X2GO_AGENT_PID=$2
X2GO_SESSION=$3
ARTS_SERVER=localhost:$4
cmd=$5
export DISPLAY
export X2GO_AGENT_PID
export X2GO_SESSION
export ARTS_SERVER
$cmd 

kill -9 $X2GO_AGENT_PID


sudo x2gopgwrapper changestatus 'F' $X2GO_SESSION  > /dev/null

export HOSTNAME
x2goumount_session $X2GO_SESSION
