#!/usr/bin/perl
use strict;

my $fname=shift;
open(F,"<$fname") or die "can't open $fname";
my $dir=<F>;
my $session=<F>;
close(F);

$session=~s/\n//;

chomp($dir);
my $uname=$ENV{'USER'};

my $use_zenity=0;

if($ENV{'GNOME_DESKTOP_SESSION_ID'} ne "")
{
     $use_zenity=1;
}

if(system( "fusermount -u $dir" ) == 0)
{
     unlink($fname);
     system("sudo x2gopgwrapper deletemount $session \"$dir\"");
     rmdir ($dir);
}
else
{
    if($use_zenity == 0)
    {
         system("kdialog --error \"Can't umount:\n $dir\"&");
    }
    else
    {
         system("zenity --error --text \"Can't umount:\n $dir\"&");
    }
}
