#!/usr/bin/perl
use strict;


sub check_stat
{
   my $sess=shift;
   my $log="$ENV{'HOME'}/.x2go/C-$sess/session.log";
   my $text=`tail -1 $log`;
   if($text =~ m/Session suspended/)
   {
       return 0;
   }
   return 1;
}

my $serv=shift;
if( ! $serv)
{
   $serv=$ENV{'HOSTNAME'};
}
my $uname=$ENV{'USER'};
my $outp;
if($serv eq "--all-servers")
{
 $outp=`sudo x2gopgwrapper listsessions_all`;
}
else
{
 $outp=`sudo x2gopgwrapper listsessions $serv`;
}

my @outp=split("\n","$outp");
for(my $i=0;$i<@outp;$i++)
{
     @outp[$i] =~ s/ //g;
     @outp[$i] =~ s/\*/ /g;
     my @sinfo=split('\\|',"@outp[$i]");
     if(@sinfo[4]eq 'F')
     {
           print "@outp[$i]\n";
     }       
     else
     { 
       if(@sinfo[4]eq 'R')
       {
           if(!check_stat(@sinfo[1]))
	   {
               system("sudo x2gopgwrapper changestatus 'S' @sinfo[1] > /dev/null");
	       @outp[$i] =~ s/\|R\|/\|S\|/;
               system( "x2goumount_session @sinfo[1]");

	   }
       }       
       print "@outp[$i]\n";
     }
}
