#!/bin/bash

SESSION_NAME=$1
X2GO_AGENT_PID=`sudo x2gopgwrapper getagent $SESSION_NAME` 
X2GO_AGENT_PID=`echo "$X2GO_AGENT_PID"| awk {'print $1'}`

sudo x2gopgwrapper changestatus 'F' $SESSION_NAME  > /dev/null

kill -TERM $X2GO_AGENT_PID
export HOSTNAME
x2goumount_session $SESSION_NAME
