#!/usr/bin/perl
use strict;

my $type=shift;
my $session=shift;
my $user=shift;
my $key=shift;
my $dirlist=shift;

my $host=(split(" ",$ENV{'SSH_CLIENT'}))[0];
print "Host:$host\n";
print "User:$user\n";

open (F,"<$key");
my @lines=<F>;
close(F);

my $lines=join("",@lines);
my $dsa_key=(split("----BEGIN RSA IDENTITY----",$lines))[0];
my $rsa_identity=(split("----BEGIN RSA IDENTITY----",$lines))[1];

open (F,">$key");
print F $dsa_key;
close(F);

open (F,">$key.ident");
print F "$host $rsa_identity";
close(F);

#my $mdir="/tmp/$ENV{'USER'}_media";
my $mdir="$ENV{'HOME'}/media";
mkdir($mdir);

my $uname=$ENV{'USER'};

my @dirs=split(':',$dirlist);
for(my $i=0;$i<@dirs;$i++)
{
       my $p=@dirs[$i];
       if($type ne "dir")
       {
           $p=~s/\/ramdrive\/mnt\///;
       }
       $p=~s/\//_/g;
       mkdir("$mdir/$p");
       my $mntpath="$mdir/$p";
       my $outp=`sudo x2gopgwrapper insertmount $session \"$mntpath\" $host`;
       if($outp =~ m/INSERT/)
       {
            print "inserted, sshfs  -o IdentityFile=$key,UserKnownHostsFile=$key.ident $user\@$host:@dirs[$i] $mdir/$p\n";
            if(system("sshfs  -o IdentityFile=$key,UserKnownHostsFile=$key.ident $user\@$host:@dirs[$i] $mdir/$p")==0)
            {   
        	print "mount @dirs[$i] ok\n";
        	my $fname="$ENV{'HOME'}/Desktop";
		$p=@dirs[$i];
        	$p=~s/\//%2f/g;
		$fname="$fname/$p";
		if($type eq "dir")
		{
	    	    $fname="$fname(sshfs-disk)";
		}
		else
		{
	    	    $fname="$fname(sshfs-removable)";
		    $fname=~s/%2framdrive%2fmnt%2f//;
		}
		print "fname: $fname\n";
		open(F,">$fname");
		print F "$mntpath\n$session";
		close(F);
    	    }
    	    else
    	    {
               print "mount @dirs[$i] failed\n";
               `sudo x2gopgwrapper deletemount $session \"$mntpath\"`;
	       rmdir($mntpath);
    	    }
       }
       else
       {
            print "insertion failed(already mounted?), not mounting\n";
       }
}

unlink($key);
unlink("$key.ident");
