#!/usr/bin/perl

use File::Basename;
use File::Copy;
use File::Path;
use strict;

use lib "/usr/lib/x2go";
use x2godbwrapper;

if (scalar(@ARGV) ==1)
{
     system ("su @ARGV[0] -c \"x2golistsessions --all-servers\" ");
}
elsif (scalar(@ARGV) != 4)
{
    print STDERR "ERROR: Usage:\nx2goprint user session file titleFile\nx2goprint user\n";
    exit 1;
}

my ($user, $session, $file, $titleFile)=@ARGV;

my ($tm,$tm,$uid,$gid,$tm,$tm,$tm,$homedir)=getpwnam("x2goprint");
my $printdir=$homedir;

my $title;
if( -e "$printdir/$titleFile")
{
     open (TITLE,"<$printdir/$titleFile");
     $title=<TITLE>;
     close (TITLE);
     unlink("$printdir/$titleFile");
}


($tm,$tm,$uid,$gid,$tm,$tm,$tm,$homedir)=getpwnam($user);

my $spoolbase="/tmp/spool_$user";
my $spooldir="$spoolbase/$session";
my $spooltmp="$spoolbase/tmp";
mkpath($spooltmp);
chown $uid, $gid, "$spooltmp";
chmod 0700, "$spooltmp";

my ($mounts)=db_getmounts($session);
if( $mounts=~m/$spooldir/)
{
     move("$printdir/$file", "$spooltmp") or die "$!: Can't move $file to $spooltmp/";
     chown $uid, $gid, "$spooltmp/$file";
     system("su $user -c \"mv $spooltmp/$file $spooldir\"");

     open (RFILE,">$spooltmp/$file.ready");
     print RFILE "$file\n$title";
     close (RFILE);

     chown $uid, $gid, "$spooltmp/$file.ready";
     system ("su $user -c \"mv $spooltmp/$file.ready $spooldir\"");
}
else
{
     unlink("$printdir/$file");
}
