#!/bin/bash

SESSION_NAME=$1


X2GO_AGENT_PID=`x2gogetagent $SESSION_NAME` 
X2GO_AGENT_PID=`echo "$X2GO_AGENT_PID"| awk {'print $1'}`


#workaround for knotify
killall -HUP knotify

x2gochangestatus 'S' $SESSION_NAME  > /dev/null


kill -HUP $X2GO_AGENT_PID

export HOSTNAME 
x2goumount_session $SESSION_NAME
