'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2goversion 8 "29 May 2011" "Version 3.0.99.x" "X2go Server Tool"
.SH NAME
x2goversion \- Retrieve Code Versions of X2go Server Components
.SH SYNOPSIS
'nh
.fi
.ad l
\fBx2goversion [<x2go-component>]\fR

.SH DESCRIPTION
\fBx2goversion\fR allows to retrieve code versions of X2go server components.
.PP
If the
\fB[<x2go-component>]\fR parameter is omitted then a list of all available X2go server
component names and versions is listed.
.PP
If an X2go component is specified with the \fB[<x2go-component>]\fR parameter, then only the
component's version is printed to stdout.
.PP
The \fBx2goversion\fR tool can be used by X2go client implementations to query server-side versions
of X2go components.
.PP
.SH FILES
/usr/share/x2go/versions/VERSION.*
.PP
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2go project
(http://www.x2go.org).
