'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2goversion 8 "Mar 2012" "Version 4.0.1.14" "X2Go Server Tool"
.SH NAME
x2goversion \- Retrieve Code Versions of X2Go Server Components
.SH SYNOPSIS
'nh
.fi
.ad l
x2goversion [<x2go-component>]

.SH DESCRIPTION
\fBx2goversion\fR allows to retrieve code versions of X2Go server components.
.PP
If the
\fB[<x2go-component>]\fR parameter is omitted then a list of all available X2Go server
component names and versions is listed.
.PP
If an X2Go component is specified with the \fB[<x2go-component>]\fR parameter, then only the
component's version is printed to stdout.
.PP
The \fBx2goversion\fR tool can be used by X2Go client implementations to query server-side versions
of X2Go components.
.SH RETURN VALUES
\fBx2goversion\fR reports X2Go component version information to stdout.
.PP
As exitcode \fBx2goversion\fR always returns 0.
.SH FILES
/usr/share/x2go/versions/VERSION.*
.PP
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(http://www.x2go.org).
