'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2gofeaturelist 8 "Feb 2018" "Version 4.1.0.1" "X2Go Server Tool"
.SH NAME
x2gofeaturelist \- Query X2Go Feature List for X2Go Server
.SH SYNOPSIS
'nh
.fi
.ad 1
x2gofeaturelist

.SH DESCRIPTION
\fBx2gofeaturelist\fR allows client applications to query a server-side list of X2Go features.
Such a list is very handy when new X2Go clients connect to older X2Go server. The list of features
provides an overview to the client on what functionalities the server support and what not.
.PP
\fBx2gofeaturelist\fR can be run with user privileges.
.SH RETURN VALUES
List of X2Go feature names.
.SH SEE ALSO
/usr/share/x2go/x2gofeature.d/*.features
x2gofeature(8)
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(http://www.x2go.org).
