'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2golistdesktops 8 "Apr 2014" "Version 4.0.1.15" "X2Go Server Tool"
.SH NAME
x2golistdesktops \- List Available X Desktops
.SH SYNOPSIS
'nh
.fi
.ad l
x2golistdesktops [<server_hostname>]

.SH DESCRIPTION
\fBx2golistdesktops\fR returns a list of active desktop sessions running on server <server_hostname>.
If no server hostname is given at the command line, the fully qualified domain name of the local system
is used here.
.PP
\fBx2golistdesktops\fR is run with X2Go user privileges and it is used by X2Go clients to render
a list of available desktops that may be candidates for X2Go desktop sharing (shadow sessions).
.PP
The list of desktops will include local desktop sessions (launched via KDM, GDM, etc.) run by the same user, X2Go desktop
sessions run by the same user and desktop sessions of other users (local or remote) that are announced via
the \fBx2godesktopsharing\fR utility.
.SH RETURN VALUES
A list of available X desktops, line-by-line.
.PP
As exitcode \fBx2golistdesktop\fR always returns 0.
.SH SEE ALSO
x2godesktopsharing(1)
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(http://www.x2go.org).
