'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2gofeature 8 "Jul 2018" "Version 4.1.0.2" "X2Go Server Tool"
.SH NAME
x2gofeature \- Query X2Go Feature Availability on X2Go Server
.SH SYNOPSIS
'nh
.fi
.ad 1
x2gofeature \fI<feature_name>\fR

.SH DESCRIPTION
\fBx2gofeature\fR allows client applications to query the server for certain features
before trying to use them.
.PP
\fBx2gofeature\fR can be run with user privileges.
.SH RETURN VALUES
If feature \fI<feature_name>\fR is available on the X2Go server, then ,,ok'' is written to stdout.
Otherwise the expression ,,not available'' is written to stdout.
.SH SEE ALSO
/usr/share/x2go/x2gofeature.d/*.features
x2gofeaturelist(8)
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(http://www.x2go.org).
