'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2gocmdexitmessage 8 "Aug 2018" "Version 4.1.0.3" "X2Go Server Tool"
.SH NAME
x2gocmdexitmessage \- Exit Message of X2Go Command
.SH SYNOPSIS
'nh
.fi
.ad l
x2gocmdexitmessage \fI<session_id>\fR

.SH DESCRIPTION
\fBx2gocmdexitmessage\fR prints out the exit message of the last command run with \fBx2goruncommand\fR for session \fI<session_id>\fR.

\fBx2gocmdexitmessage\fR is run with X2Go user privileges.
.PP
.SH RETURN VALUES
\fBx2gocmdexitmessage\fR prints out the last command's exit message.
.PP
As exitcode \fBx2gocmdexitmessage\fR always returns 0.
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(https://www.x2go.org).
