'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2godbadmin 8 "Apr 2014" "Version 4.0.1.15" "X2Go Server Admin Tool"
.SH NAME
x2godbadmin \- X2Go Server Database Administrator
.SH SYNOPSIS
'nh
.fi
.ad l
x2godbadmin <options>

.SH DESCRIPTION
\fBx2godbadmin\fR is used to set up the initial X2Go session database and perform other
maintenance tasks on the X2Go server's database.
.PP
\fBx2godbadmin\fR must be run with root privileges.
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(http://www.x2go.org).
