'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2gosessionlimit 8 "Jan 2013" "Version 4.1.0.0-preview" "X2Go Server Tool"
.SH NAME
x2gosessionlimit \- Detect Session Limit for User or Group
.SH SYNOPSIS
'nh
.fi
.ad 1
x2gosessionlimit

.SH DESCRIPTION
\fBx2gosessionlimit\fR is not yet documented as a man page... TODO!
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(http://www.x2go.org).
