'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2golistsessions_root 8 "Sep 2011" "Version 3.0.99.x" "X2go Server Admin Tool"
.SH NAME
x2golistsessions_root \- List X2go Sessions for System
.SH SYNOPSIS
'nh
.fi
.ad l
x2golistsessions_root [<server_hostname>]

.SH DESCRIPTION
\fBx2golistsessions_root\fR shows a list of all available X2go sessions on the server <server_hostname>.
If no server hostname is given at the command line, the session list query runs for the local system.
.PP
\fBx2golistsessions_root\fR must be run with root privileges.
.PP
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2go project
(http://www.x2go.org).
