'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2goresume-session 8 "Mar 2012" "Version 3.1.1.x" "X2Go Server Tool"
.SH NAME
x2goresume-session \- Resume X2Go Session
.SH SYNOPSIS
'nh
.fi
.ad l
x2goresume-session <session_id>

.SH DESCRIPTION
\fBx2goresume-session\fR resumes the suspended session with session ID <session_id>.
.PP
This command is normally issued
by an X2Go client application with X2Go user privileges.
.SH RETURN VALUES
\fBx2goresume-session\fR reports to stderr if resuming of session <session_id> failed. This
very probably means that the session's X agent has died, so the session <session_id> will
be marked as finished in the X2Go session database.
.PP
As exitcode \fBx2goresume-session\fR always returns 0.
.SH SEE ALSO
x2gostartagent(8), x2goruncommand(8), x2gosuspend-session(8), x2goterminate-session(8)
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(http://www.x2go.org).
