#!/usr/bin/perl

# Copyright (C) 2007-2011 X2go Project - http://wiki.x2go.org
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#
# Copyright (C) 2007-2011  Oleksandr Shneyder <oleksandr.shneyder@obviously-nice.de>
# Copyright (C) 2007-2011  Heinz-Markus Graesing <heinz-m.graesing@obviously-nice.de>

use strict;
use Sys::Hostname;
use Sys::Syslog qw( :standard :macros );

use lib `echo -n \$(x2gobasepath)/lib/x2go`;
use x2gologlevel;

openlog($0,'cons,pid','user');
setlogmask( LOG_UPTO(x2gologlevel()) );


sub check_stat
{
	my $sess=shift;
	my $user=shift;
	my $log="~$user/.x2go/C-$sess/session.log";
	my $text=`tail -1 $log`;
	if ($text =~ m/Session suspended/)
	{
		return 0;
	}
	return 1;
}

my $uname;

my $serv=shift;
if ( ! $serv)
{
	$serv=hostname;
}

my $outp=`x2golistsessions_sql $serv 2>/dev/null`;


my @outp=split("\n","$outp");

for (my $i=0;$i<@outp;$i++)
{
	my @sinfo=split('\\|',"@outp[$i]");
	if (@sinfo[4]eq 'F')
	{
		print "@outp[$i]\n";
	}
	else
	{ 
		if (@sinfo[4]eq 'R')
		{
			if (!check_stat(@sinfo[1],@sinfo[11]))
			{
				system("su - @sinfo[11] -c \"x2gochangestatus 'S' @sinfo[1]\" > /dev/null");
				@outp[$i] =~ s/\|R\|/\|S\|/;
			}
		}
		syslog('debug', "x2golistsessions_root has been called...");
		print "@outp[$i]\n";
	}
}

# closing syslog 
closelog;