#!/usr/bin/perl

# Copyright (C) 2014 X2Go Project - http://wiki.x2go.org
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#
# Copyright (C) 2014 Guangzhou Nianguan Electronics Technology Co.Ltd. <opensource@gznianguan.com>
# Copyright (C) 2014 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
#

use strict;
use X2Go::Server qw(get_session_info);
use X2Go::Utils qw(check_x2go_sessionid test_socket_state);


my $doRetryCnt = 5;
my $X2GoSID = check_x2go_sessionid;

my @X2GoSesINFO = get_session_info($X2GoSID);
if (@X2GoSesINFO[1] eq $X2GoSID) {
	while ($doRetryCnt > 0) {
		$doRetryCnt--;
		if (test_socket_state($X2GoSesINFO[8])) {
			exit;
		} 
		sleep 1;
	}
}
