#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

LASTVERSION=$2

if dpkg --compare-versions "$LASTVERSION" lt "3.1.0.0" && \
   [ -e /etc/x2go/x2gosql/sql ] && \
   egrep "^backend=postgres.*" /etc/x2go/x2gosql/sql >/dev/null; then

	db_input critical x2goserver/postgresql-upgrade-3_1_0_0 || true
	db_go

fi

if dpkg --compare-versions "$LASTVERSION" lt "4.1.0.0" && \
   [ -e /etc/x2go/x2gosql/sql ] && \
   egrep "^backend=postgres.*" /etc/x2go/x2gosql/sql >/dev/null; then

	db_input critical x2goserver/upgrade-4_1_0_0 || true
	db_go

fi