Document: x2goserver
Title: Debian x2goserver Manual
Author: <insert document author here>
Abstract: This manual describes what x2goserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/x2goserver/x2goserver.sgml.gz

Format: postscript
Files: /usr/share/doc/x2goserver/x2goserver.ps.gz

Format: text
Files: /usr/share/doc/x2goserver/x2goserver.text.gz

Format: HTML
Index: /usr/share/doc/x2goserver/html/index.html
Files: /usr/share/doc/x2goserver/html/*.html

  
