x2goserver/bin/x2go*                    /usr/bin/
x2goserver/sbin/x2go*                   /usr/sbin/
x2goserver/lib/x2go*                    /usr/lib/x2go/
x2goserver/etc/x2gosql/sql              /etc/x2go/x2gosql/
x2goserver/etc/x2goserver.conf          /etc/x2go/
x2goserver/VERSION.x2goserver           /usr/share/x2go/versions/
x2goserver/x2gosqlitewrapper            /usr/lib/x2go/
x2goserver/x2goprint                    /usr/bin/x2goprint

