#!/usr/bin/perl
# Copyright (C) 2007-2014 X2Go Project - http://wiki.x2go.org
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
#
# Copyright (C) 2007-2014 Oleksandr Shneyder <oleksandr.shneyder@obviously-nice.de>
# Copyright (C) 2007-2014 Heinz-Markus Graesing <heinz-m.graesing@obviously-nice.de>

use strict;
use Sys::Hostname;
use Sys::Syslog qw( :standard :macros );

use lib `x2gopath lib`;
use x2gologlevel;


openlog($0,'cons,pid','user');
setlogmask( LOG_UPTO(x2gologlevel()) );


sub is_suspended
{
	my $state=get_agent_state(@_);
	if(($state eq 'SUSPENDING')||($state eq 'SUSPENDED'))
	{
		return 1;
	}
	return 0;
}

sub has_agent_state_file
{
	my $sess=@_[0];
	my $user=@_[1];
	my $stateFile;
	if ( -d "/tmp-inst/${user}/.x2go-${user}" ) {
		$stateFile="/tmp-inst/${user}/.x2go-".$user."/C-".$sess."/state";
	} else {
		$stateFile = "/tmp/.x2go-".$user."/C-".$sess."/state";
	}
	if ( -e $stateFile )
	{
		return 1;
	}
	return 0;
}

sub get_agent_state
{
	my $sess=@_[0];
	my $user=@_[1];
	my $state;
	my $stateFile = "/tmp/.x2go-".$user."/C-".$sess."/state";
	if (! -e $stateFile )
	{
		syslog('warning', "$sess: state file for this session does not exist: $stateFile (this can be ignored during session startups)");
		$state="UNKNOWN";
	}
	else
	{
		open(F,"<$stateFile");
		$state=<F>;
		close(F);
	}
	return $state;
}


my $x2go_lib_path = `x2gopath libexec`;

my $uname;

my $serv=shift;
if ( ! $serv)
{
	$serv=hostname;
}

my $outp=`$x2go_lib_path/x2golistsessions_sql $serv 2>/dev/null`;

my @outp=split("\n","$outp");

for (my $i=0;$i<@outp;$i++)
{
	my @sinfo=split('\\|',"@outp[$i]");
	if (@sinfo[4]eq 'F') {
		print "@outp[$i]\n";
	} else {
		if (has_agent_state_file(@sinfo[1],@sinfo[11]))
		{
			if (@sinfo[4]eq 'R')
			{
				if (is_suspended(@sinfo[1],@sinfo[11]))
				{
					system("su", "@sinfo[11]", "-s", "/bin/sh", "-c", "$x2go_lib_path/x2gochangestatus 'S' @sinfo[1] > /dev/null");
					@outp[$i] =~ s/\|R\|/\|S\|/;
				}
			}
		}
		print "@outp[$i]\n";
	}
}
