#!/usr/bin/perl

# Copyright (C) 2007-2018 X2Go Project - https://wiki.x2go.org
# Copyright (C) 2007-2018 Oleksandr Shneyder <o.shneyder@phoca-gmbh.de>
# Copyright (C) 2007-2018 Heinz-Markus Graesing <heinz-m.graesing@obviously-nice.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the
# Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.

use strict;
use Sys::Hostname;
use Sys::Syslog qw( :standard :macros );

use X2Go::Log qw(loglevel);
use X2Go::Utils qw(system_capture_stdout_output);
use X2Go::Server::Agent qw(session_is_suspended has_agent_state_file);
my $x2go_lib_path = system_capture_stdout_output("x2gopath", "libexec");

openlog($0,'cons,pid','user');
setlogmask( LOG_UPTO(loglevel()) );


my $uname;

my $serv=shift;
if ( ! $serv)
{
	$serv=hostname;
}

my $outp=system_capture_stdout_output("$x2go_lib_path/x2golistsessions_sql","$serv");

my @outp=split("\n","$outp");

for (my $i=0;$i<@outp;$i++)
{
	my @sinfo=split('\\|',"@outp[$i]");
	if (@sinfo[4]eq 'F') {
		print "@outp[$i]\n";
	} else {
		if (has_agent_state_file(@sinfo[1],@sinfo[11]))
		{
			if (@sinfo[4]eq 'R')
			{
				if (session_is_suspended(@sinfo[1],@sinfo[11]))
				{
					system("su", "@sinfo[11]", "-s", "/bin/sh", "-c", "$x2go_lib_path/x2gochangestatus 'S' @sinfo[1] > /dev/null");
					@outp[$i] =~ s/\|R\|/\|S\|/;
				}
			}
		}
		print "@outp[$i]\n";
	}
}
