'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2gosetkeyboard 8 "31 May 2011" "Version 3.0.99.x" "X2go Server Tool (Extension)"
.SH NAME
x2gosetkeyboard \- Allow server-side Keyboard Setting Updates issued by X2go Client
.SH SYNOPSIS
'nh
.fi
.ad l
x2gosetkeyboard

.SH DESCRIPTION
\fBx2gosetkeyboard\fR looks for a 'keyboard' file in the X2go session directory and introspects
the X2go session keyboard settings requested from the client side.
.PP
If no 'keyboard' file is present in the X2go session directory, nothing happens (i.e. no error
will be raised).
.SH RETURN VALUES
If \fBx2gosetkeyboard\fR successfully sets the session's keyboard parameters an exit code of 0 is
returned. Also, if the file ${HOME}/.x2go/C-${X2GO_SESSION}/keyboard is not presented at the
expected location, a zero-exitcode is returned.
.PP
If the command fails on its way, then the exitcode of the failing command is returned.
.SH FILES
${HOME}/.x2go/C-${X2GO_SESSION}/keyboard
.PP
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2go project
(http://www.x2go.org).
