'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2gofm 8 "Sep 2012" "Version 3.2.x.y" "X2Go Server"
.SH NAME
x2gofm \- X2Go wrapper for Browsing X2Go Shared Folders
.SH SYNOPSIS
'nh
.fi
.ad l
x2gofm <shared-folder>

.SH DESCRIPTION
\fBx2gofm\fR is a component of the generic file manager bindings for X2Go's shared folders.
\fBx2gofm\fR uses XDG (namely x2go-open <dir>) to launch the default file browser on all
client-side folders shared via X2Go.
.PP
The default file browser is defined by the freedesktop.org specification of the running desktop
environment.
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2go project
(http://www.x2go.org).
