'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2goterminate 1 "18 May 2011" "Version 3.0.99.x" "X2go Server Tool"
.SH NAME
x2goterminate \- X2go Server Script (deprecated, shipped for compatibility with old clients)
.SH SYNOPSIS
'nh
.fi
.ad l
x2goterminate <session-name>

.SH DESCRIPTION
\fBx2goterminate\fR is a deprecated script belonging to X2go Server. The availability of this script
is required to allow session termination from old \fBx2goclient\fR versions.
.PP
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2go project
(http://www.x2go.org).
