'\" -*- coding: utf-8 -*-
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH x2goprint 8 "Mar 2012" "Version 4.0.x.y" "X2Go Server Tool"
.SH NAME
x2goprint \- Process X2Go Print Job
.SH SYNOPSIS
'nh
.fi
.ad l
x2goprint <username> <session_id> <pdf_file> <title_file>

.SH DESCRIPTION
X2Go print jobs are rendered by the \fBcups-x2go\fR backend on your network's (central) CUPS server and
then get copied to the X2Go server that the X2Go print job was issued from.
.PP
On that X2Go server \fBcups-x2go\fR places two print job files (a PDF file and a title file)
into the home directory of the POSIX system user ,,x2goprint'' where they await further processing
by \fBx2goprint\fR.
.PP
The \fBx2goprint\fR command on the session's X2Go server (executed by \fBcups-x2go\fR backend) then
prepares the job files for delivery to the X2Go client-side.
.PP
\fBx2goprint\fR must run with root privileges and is executed by \fBcups-x2go\fR.
.SH ARGUMENTS
.TP
\*(T<\fB\<username>\fR\*(T>
The owner of the incoming print jobs is given as the <username> argument.
.TP
\*(T<\fB\<session_id>\fR\*(T>
The <session_id> is the unique identifier of the X2Go session that the processed print job is
coming from.
.TP
\*(T<\fB\<pdf_file>\fR\*(T>
The filename of the PDF file as dropped into ~x2goprint by \fBcups-x2go\fR.
.TP
\*(T<\fB\<title_file>\fR\*(T>
The filename of the title file as dropped into ~x2goprint by \fBcups-x2go\fR.
.PP
.SH PERMISSIONS
X2Go uses the fuse-based SSH filesystem (SSHFS) for transferring print jobs from X2Go server to X2Go client.
Users that shall use X2Go printing must be members of the X2Go server's ,,fuse'' POSIX group.
.PP
.SH X2GO CLUSTER MODE
If X2Go server and CUPS server are the same machine, no further setup for X2Go printing is necessary.
.PP
However, if X2Go server and CUPS server are hosted on separate machines then a special setup of sudo and SSH
is required on X2Go server(s) and the central CUPS server.
.PP
Refer to http://wiki.x2go.org/installing_x2go_printing_debian_ubuntu for further information.
.PP
.SH RETURN VALUES
By \fBx2goprint\fR nothing is reported on stdout or stderr.
.PP
If \fBx2goprint\fR has run successfully, an exitcode of 0 is returned. If the script has either been
called by a non-root user or with the wrong number of command line arguments, a non-zero exitcode is
returned.
.SH AUTHOR
This manual has been written by Mike Gabriel <mike.gabriel@das-netzwerkteam.de> for the X2Go project
(http://www.x2go.org).
